language: node_js
node_js:
    - "stable"
before_script:
    - npm install 
script:
    - npm run build  
# safelist
branches:
    only:
    - master 

cache:
  directories:
  - node_modules
# before_script:
  #- npm install -g gulp-cli
#script:
 # - npm test
 # - npm run build

  # Added the test comment on develop branch
before_deploy: "echo 'I am ready to deploy to S3 Bucket'"
deploy:
    provider: s3
    access_key_id: "ASIAJLVYNHUWCPKOPSYQ"
    secret_access_key: "DcCc9H6oCkGUSp3Rhmsx8NIfVG8kO2T/3jORxuZY"
    bucket: "S3 Bucket"
    skip_cleanup: true
    local_dir: build
    upload-dir: travis-builds
    on:
      branch: master
after_deploy: "echo 'I done with the deploy to S3 Bucket. Please check the Logs'"
