--- 
after_deploy: "echo 'I done with the deploy to S3 Bucket. Please check the Logs'"
before_deploy: "echo 'I am ready to deploy to S3 Bucket'"
before_script: 
  - "echo \"node version $(node -v) running\""
  - "echo \"The Access Name is $access_key_id\""
  - "echo \"The Branch Name is $CURRENT_BRANCH\""
branches: 
  only: 
    - master
cache: 
  directories: 
    - node_modules
language: node_js
node_js: 
  - stable
script: ~
