language: node_js
node_js:
    - "stable"
before_script:
    - npm install 
    # - git submodule update --init --recursive

script:
   - npm run build  
# safelist
branches:
    only:
    - master 
cache:
  directories:
  - node_modules

# before_deploy:
before_deploy: 
   - "echo 'I am ready to deploy to S3 Bucket'"
   - "echo 'Access Key $access_key_id'"
   - "echo 'branch name $CURRENT_BRANCH'"
   - "echo 'foo' $foo"
deploy:
    provider: s3
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    bucket: "cdn.fusioncharts.com"
    skip_cleanup: true
    local_dir: build
    upload-dir: fusioncharts/fc-testdevelop
    region: eu-central-1
    #acl: public_read
    on:
      branch: master
after_deploy: "echo 'I done with the deploy to S3 Bucket. Please check the Logs'"

# Test Comment to test the Travis Build - v4
